version: "3"
services:
  okmtyuta-engineering-api:
    container_name: "okmtyuta-engineering-api"
    build:
      context: .
      dockerfile: ./packages/presentation/rest-api/okmtyuta-engineering-api/Dockerfile
    tty: true
    volumes:
      - ./packages/presentation/rest-api/okmtyuta-engineering-api:/okmtyuta/packages/presentation/rest-api/okmtyuta-engineering-api/
    ports:
      - 8001:8001
    command: npm run start-api:dev

  database:
    image: postgres:14.6
    tty: true
    environment:
      POSTGRES_DB: okmtyuta
      POSTGRES_USER: okmtyuta
      POSTGRES_PASSWORD: s#kn18k0a0
    ports:
      - 5432:5432
